import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Projects @ Vignesh T D",
  description: "Generated by create next app",
};

export default function Projects(){
    return(

        <>
        hai
        </>
    );
}